name: Release on GitHub Packages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags: [v*]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Publish on GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: 📁 Checkout
        uses: actions/checkout@v6

      - name: 📦 Install bun
        uses: oven-sh/setup-bun@v2

      - name: ⚙️ Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          registry-url: https://npm.pkg.github.com
          scope: "@opendreamnet"

      - name: 👨🏻‍💻 Install Dependencies
        run: bun install --frozen-lockfile

      - name: 🏗️ Build
        run: bun run build

      # https://github.com/oven-sh/bun/issues/24124 
      - name: 🚀 Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     